server:
  port: 4000

spring:
  application:
    name: pig-upms-biz
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: ${NACOS_HOST:192.168.0.201}:${NACOS_PORT:8848}
        namespace: 5d42b64c-af69-4a94-8189-c7e890784c35
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: 5d42b64c-af69-4a94-8189-c7e890784c35
  config:
    import:
      - nacos:application-dev.yml
      - nacos:${spring.application.name}-dev.yml


