server:
  port: 5003

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        server-addr: ${NACOS_HOST:192.168.0.201}:${NACOS_PORT:8848}
        namespace: 5d42b64c-af69-4a94-8189-c7e890784c35
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: 5d42b64c-af69-4a94-8189-c7e890784c35
  config:
    import:
      - nacos:application-@profiles.active@.yml
      - nacos:${spring.application.name}-@profiles.active@.yml

management:
  endpoints:
    web:
      exposure:
        include: "*"   # 暴露所有端点
  endpoint:
    health:
      show-details: ALWAYS  # health 显示详细信息
  server:
    port: ${server.port}    # ⚠️ 建议和 server.port 一致，不要分离


